version: "3"
services:
  server:
    # restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - ./backend:/backend
    depends_on:
      - mongo
  client:
    # restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
